### PR TITLE
[TODO] Set up CI with Azure Pipelines

### PR DESCRIPTION
**Pull request by timotheecour**
a few notes while playing w converting travis.yml to azure:
* azure kills previous jobs if you push a new commit (may or may not be a good thing)
* colors are gone from logs eg https://dev.azure.com/timotheecour/timotheecour/_build/results?buildId=3

### CODE REVIEW

**Comment by fredrikhr** [comment]
Pro Tip:
Split up the pipeline into multiple tasks. That way it easier to see if it is the git clone, the building of koch or running of koch that fails

**Comment by fredrikhr** [comment]
@timotheecour 
* killing previous jobs is something you can configure
* colouring IS definitely possible

We'll deal with that once we start getting things going

**Comment by timotheecour** [comment]
EDIT: I'm getting colors after all:
image

**Comment by timotheecour** [comment]
@couven92 ouch I'm getting a dreadful `out of memory`; too bad, as it's the only single error in the test suite :(
if u have any tips on that, otherwise I'll do some research

```
2019-01-18T13:45:58.9573733Z testament/tester --nim:compiler/nim pcat stdlib 
2019-01-18T13:46:01.7032535Z ‌FAIL: ‌tests/system/t7894.nim C‌
2019-01-18T13:46:01.7033065Z ‌Test "tests/system/t7894.nim" in category "system"‌
2019-01-18T13:46:01.7041193Z ‌Failure: reExitcodesDiffer‌
2019-01-18T13:46:01.7041855Z ‌Expected:‌
2019-01-18T13:46:01.7042394Z ‌exitcode: 0‌
2019-01-18T13:46:01.7042876Z ‌
2019-01-18T13:46:01.7043353Z ‌Gotten:‌
2019-01-18T13:46:01.7043848Z ‌exitcode: 1‌
2019-01-18T13:46:01.7044282Z 
2019-01-18T13:46:01.7044498Z Output:
2019-01-18T13:46:01.7044678Z out of memory
```

EDIT: saw https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits but couldn't find answer

EDIT: figured out how to fix this!

**Pull request closed without merging**
