### PR TITLE
10X faster toUpperAsciiInPlace using general optimization trick for conditional array writes

### PR DESCRIPTION
**Pull request by timotheecour**
this seems like a general optimization strategy we could use in other places:

this
```nim
    for c in mitems(s):
      c = chr(c.ord + (if c.isUpperAscii: (ord('a') - ord('A')) else: 0))
```

is 11X faster than:

```nim
    for c in mitems(s):
      if c.isUpperAscii: c = chr(ord(c) + (ord('a') - ord('A')))
```

## benchmark
https://github.com/timotheecour/vitanim/blob/master/testcases/t10332d.nim
git clone https://github.com/timotheecour/vitanim && cd vitanim
```
nim c -r --skipparentcfg --skipusercfg --hints:off -d:danger --lib:lib -f $vitanim_D/testcases/t10332d.nim
```
6.1570 for this https://github.com/nim-lang/Nim/pull/13610
0.573082 for this PR https://github.com/timotheecour/Nim/pull/54

## scratch below here
* maybe (or not...) related: https://stackoverflow.com/questions/11276291/why-cant-or-doesnt-the-compiler-optimize-a-predictable-addition-loop-into-a
* https://stackoverflow.com/questions/11227809/why-is-processing-a-sorted-array-faster-than-processing-an-unsorted-array
* maybe it relates to write hazards and branch prediction; writing on contiguous memory locations (as I'm doing here) seems to be faster than writing at random array locations

### CODE REVIEW

**Comment by ringabout** [comment]
Rebase the commits? It is not easy to see the implementation.

**Comment by ringabout** [comment]
And `toUpperAscii` has already a new faster implementation using bit operation BTW.

**Comment by timotheecour** [comment]
> Rebase the commit

hard because (as you said) `toUpperAscii` was already updated; this PR is less relevant now, but the main idea was the optimzation trick used in the PR which is a subtle point that's re-usable in other contexts; closing

**Comment by ringabout** [comment]
This should be faster I guess :)
https://github.com/timotheecour/Nim/issues/422#issuecomment-739612663

**Pull request closed without merging**
